title: Yudha Prawira
logo: ![WhatsApp Image 2024-09-15 at 00,31,41_dda027e8-photoaidcom-cropped](https://github.com/user-attachments/assets/407a4e4c-4d3f-43f2-9e01-224b5f8c7103)
description: text below image
show_downloads: true
theme: jekyll-theme-minimal
